#!/usr/bin/env python3
"""Run only the complete P0 sign-in simulator matrix, never release/IPA acceptance.

The source is generated by the same function used by the production shell
patcher. No upstream checkout, synthetic prepared host, legacy rendering build,
backend connection, or IPA is needed. Requires macOS, Xcode and an installed
iOS runtime with both an iPhone and an iPad simulator.
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
from pathlib import Path
import platform
import plistlib
import re

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = "p0-preflight-verification.json"


def load_script(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


p0 = load_script("run_p0_signin_rendering")
rendering = load_script("run_issue25_rendering")
shell = load_script("patch_v3_unified_shell")


def write_json(path: Path, value: dict) -> None:
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    temporary.replace(path)


def input_hashes() -> dict:
    """Hash executable harness, generation inputs and fixture inputs, not just HEAD."""
    paths = [Path(__file__).resolve(), ROOT / "scripts/run_p0_signin_rendering.py",
             ROOT / "scripts/run_issue25_rendering.py", ROOT / "scripts/patch_v3_unified_shell.py",
             shell.BEHAVIOR_TEMPLATE, shell.SECRET_HANDOFF_TEMPLATE,
             shell.IPA_STAGING_TEMPLATE, shell.TEMPLATE,
             *(ROOT / "scripts/templates" / name for name in (
                 "v3_wire_contract.swift", "v3_service_bridge.swift", "combined_failure.swift")),
             ROOT / "tests/fixtures/p0_signin_app.swift", ROOT / "tests/fixtures/p0_signin_ui_tests.swift"]
    paths.extend(path for path in (ROOT / "tests/fixtures/p0_signin_project").rglob("*") if path.is_file())
    return {str(path.relative_to(ROOT)): p0.digest(path) for path in sorted(paths)}


def prepare_source(output: Path, prepared_shell: Path | None = None) -> tuple[Path, dict]:
    source = output / "production-source/V3UnifiedShell.swift"
    source.parent.mkdir()
    source.write_text(shell.generated_shell_source(), encoding="utf-8")
    extracted, hashes = p0.extract_sources(source, ROOT / "scripts/templates")
    identity = {"method": "patch_v3_unified_shell.generated_shell_source",
                "scope": "Exact production shell generation; not a prepared host or release build",
                "generatedSourceSHA256": p0.digest(source), "extractedSourceSHA256": hashes,
                "preparedShellComparison": "not requested"}
    if prepared_shell is not None:
        prepared_shell = prepared_shell.resolve(strict=True)
        actual, actual_hashes = p0.extract_sources(prepared_shell, ROOT / "scripts/templates")
        # Includes full V3SignInView and every unchanged extracted declaration/member.
        # The full shell may contain unrelated changes; they cannot alter this matrix.
        if actual != extracted:
            changed = sorted(name for name in set(actual) | set(extracted)
                             if actual.get(name) != extracted.get(name))
            raise ValueError("Prepared shell P0 extraction differs from production generation: " + ", ".join(changed))
        identity.update({"preparedShellComparison": "exact extracted-source equality",
                         "preparedShellPath": str(prepared_shell),
                         "preparedShellSHA256": actual_hashes["generated-shell"]})
    write_json(output / "source-generation.json", identity)
    return source, identity


def matrix_counts(reports: list[dict]) -> tuple[int, int, bool]:
    cases = screenshots = 0
    valid = len(reports) == 2 and {report.get("deviceClass") for report in reports} == {"phone", "tablet"}
    for report in reports:
        rows = report.get("cases", [])
        cases += len(rows)
        valid = valid and report.get("passed") is True and report.get("failures") == []
        valid = valid and report.get("reportCount") == 4 and len(rows) == 4
        valid = valid and {row.get("case") for row in rows} == p0.REQUIRED_CASES
        for row in rows:
            names = row.get("screenshots", [])
            screenshots += len(names)
            expected = {f"p0-{row.get('case')}-{suffix}"
                        for suffix in p0.REQUIRED_SCREENSHOTS.get(row.get("case"), set())}
            valid = valid and len(names) == 3 and set(names) == expected
    return cases, screenshots, bool(valid and cases == 8 and screenshots == 24)


def run(output: Path, prepared_shell: Path | None = None) -> dict:
    # Refuse stale evidence before writing anything, including a failure manifest.
    if output.is_symlink() or (output.exists() and (not output.is_dir() or any(output.iterdir()))):
        raise ValueError("--output must be a fresh evidence directory; previous evidence is never reused")
    output.mkdir(parents=True, exist_ok=True)
    output = output.resolve()
    manifest = {"schema": "p0-signin-preflight-v1", "schemaVersion": 1,
                "mode": "p0-signin-preflight", "preflightOnly": True,
                "releaseEligible": False, "fullSuiteValidated": False,
                "physicalDeviceExecution": False, "voiceOverSpokenOutputValidated": False,
                "backendExecution": False, "legacyReportCount": 0, "ipaBuilt": False,
                "passed": False, "status": "running", "phase": "initializing",
                "ciRun": os.environ.get("GITHUB_RUN_ID"), "builderCommit": None,
                "requiredDeviceClasses": ["phone", "tablet"], "requiredCaseCount": 8,
                "requiredScreenshotCount": 24, "devices": [], "reports": [], "failures": []}
    write_json(output / MANIFEST, manifest)
    previous_log = rendering.COMMAND_LOG
    rendering.COMMAND_LOG = output / "command-diagnostics.jsonl"
    try:
        manifest["builderCommit"] = rendering.command("git", "-C", str(ROOT), "rev-parse", "HEAD")
        if not re.fullmatch(r"[0-9a-f]{40}", manifest["builderCommit"]):
            raise ValueError("Cannot record the actual builder commit")
        manifest["builderWorkingTreeDirty"] = bool(rendering.command(
            "git", "-C", str(ROOT), "status", "--porcelain", "--", "scripts", "tests"))
        manifest["inputSHA256"] = input_hashes()
        if manifest["builderWorkingTreeDirty"]:
            raise ValueError("Builder scripts/tests have uncommitted changes; commit the exact preflight inputs first")
        manifest["phase"] = "source-generation"
        source, manifest["sourceGeneration"] = prepare_source(output, prepared_shell)
        if platform.system() != "Darwin":
            raise RuntimeError("P0 sign-in UI preflight requires macOS with Xcode and iOS simulators")
        manifest["phase"] = "build-for-testing"
        write_json(output / MANIFEST, manifest)
        prepared = p0.prepare(output, source, rendering.command)
        manifest["sourceSHA256"] = prepared["sourceSHA256"]
        info = plistlib.loads((output / "p0-signin/project/Info.plist").read_bytes())
        if info.get("LCBuilderCommit") != manifest["builderCommit"]:
            raise ValueError("Fixture builder commit differs from the preflight checkout identity")
        if prepared["sourceSHA256"].get("generated-shell") != manifest["sourceGeneration"]["generatedSourceSHA256"]:
            raise ValueError("P0 build source differs from the verified production generation")
        manifest["phase"] = "device-discovery"
        devices = rendering.available_devices()
        if (len(devices) != 2 or {kind for kind, _, _ in devices} != {"phone", "tablet"}
                or len({device for _, device, _ in devices}) != 2):
            raise ValueError("P0 preflight requires exactly one phone and one distinct tablet")
        manifest["simulatorRuntimes"] = sorted({runtime for _, _, runtime in devices})
        # Preserve the selector's phone/tablet order and never run two devices concurrently.
        for kind, device, runtime in devices:
            record = {"deviceClass": kind, "udid": device, "runtime": runtime,
                      "bootOwned": False, "shutdownAttempted": False, "failures": []}
            manifest["devices"].append(record)
            manifest["phase"] = kind + "-boot"
            execution_started = False
            try:
                state = json.loads(rendering.command("xcrun", "simctl", "list", "devices", "--json"))
                matches = [item for group in state["devices"].values() for item in group if item["udid"] == device]
                if len(matches) != 1 or matches[0]["state"] not in ("Booted", "Shutdown"):
                    raise ValueError("Selected simulator has no unambiguous Booted/Shutdown state")
                record["initialState"] = matches[0]["state"]
                if matches[0]["state"] == "Shutdown":
                    # Own this boot attempt even if simctl times out after starting it.
                    record["bootOwned"] = True
                    rendering.command("xcrun", "simctl", "boot", device)
                rendering.wait_for_simulator_boot(device)
                manifest["phase"] = kind + "-ui-tests"
                write_json(output / MANIFEST, manifest)
                execution_started = True
                report = p0.execute(prepared, kind, device, output, rendering.command)
                manifest["reports"].append(report)
                if report.get("passed") is not True:
                    record["failures"].append("P0 XCTest/export verification failed")
            except Exception as error:
                record["failures"].append(str(error))
            finally:
                if not execution_started and record.get("initialState"):
                    # execute() already captures after any test/export failure. Boot
                    # failures still get a best-effort terminal image before cleanup.
                    try:
                        p0.capture_diagnostics(output / "p0-signin", kind, device, None, rendering.command)
                    except Exception as error:
                        record["failures"].append("Boot diagnostics: " + str(error))
                if record["bootOwned"]:
                    record["shutdownAttempted"] = True
                    try:
                        rendering.command("xcrun", "simctl", "shutdown", device)
                        record["shutdownSucceeded"] = True
                    except Exception as error:
                        record["shutdownSucceeded"] = False
                        record["failures"].append("Owned simulator shutdown: " + str(error))
                write_json(output / MANIFEST, manifest)
        manifest["phase"] = "verification"
        if rendering.command("git", "-C", str(ROOT), "rev-parse", "HEAD") != manifest["builderCommit"]:
            raise ValueError("Builder commit changed during the preflight")
        if input_hashes() != manifest["inputSHA256"] or p0.digest(source) != manifest["sourceGeneration"]["generatedSourceSHA256"]:
            raise ValueError("Source or harness inputs changed during the preflight")
        manifest["caseCount"], manifest["screenshotCount"], complete = matrix_counts(manifest["reports"])
        if not complete:
            manifest["failures"].append("The complete verified two-device, eight-case, 24-screenshot matrix is required")
        manifest["passed"] = complete and not any(record["failures"] for record in manifest["devices"])
    except Exception as error:
        manifest["failures"].append(str(error))
    except BaseException as error:
        manifest["failures"].append("Interrupted: " + type(error).__name__)
        raise
    finally:
        manifest["reportCount"] = len(manifest["reports"])
        manifest.setdefault("caseCount", sum(len(report.get("cases", [])) for report in manifest["reports"]))
        manifest.setdefault("screenshotCount", sum(len(case.get("screenshots", []))
                            for report in manifest["reports"] for case in report.get("cases", [])))
        manifest["passed"] = manifest["passed"] and not manifest["failures"]
        manifest["status"] = "passed" if manifest["passed"] else "failed"
        try:
            write_json(output / MANIFEST, manifest)
        finally:
            rendering.COMMAND_LOG = previous_log
    return manifest


def run_input_diagnostic(output: Path) -> dict:
    """Two named one-shot phone observations; never a preflight acceptance run."""
    if output.is_symlink() or (output.exists() and (not output.is_dir() or any(output.iterdir()))):
        raise ValueError("--output must be a fresh evidence directory; previous evidence is never reused")
    output.mkdir(parents=True, exist_ok=True)
    output = output.resolve()
    manifest = {"schema": "p0-signin-input-diagnostic-v1", "mode": "input-diagnostic",
                "diagnosticOnly": True, "passed": False, "releaseEligible": False,
                "fullSuiteValidated": False, "ipaBuilt": False, "physicalDeviceExecution": False,
                "ciRun": os.environ.get("GITHUB_RUN_ID"), "builderCommit": None,
                "observations": [{"name": name, "status": "not-started"}
                                 for name in ("cold-launch", "fresh-app-relaunch")],
                "failures": [], "diagnosticCompleted": False}
    path = output / "input-diagnostic.json"
    write_json(path, manifest)
    previous_log = rendering.COMMAND_LOG
    rendering.COMMAND_LOG = output / "command-diagnostics.jsonl"
    owned = False
    device = None
    try:
        manifest["builderCommit"] = rendering.command("git", "-C", str(ROOT), "rev-parse", "HEAD")
        if not re.fullmatch(r"[0-9a-f]{40}", manifest["builderCommit"]):
            raise ValueError("Cannot record the actual builder commit")
        if rendering.command("git", "-C", str(ROOT), "status", "--porcelain", "--", "scripts", "tests"):
            raise ValueError("Diagnostic inputs have uncommitted changes")
        manifest["inputSHA256"] = input_hashes()
        source, manifest["sourceGeneration"] = prepare_source(output)
        if platform.system() != "Darwin":
            raise RuntimeError("Input diagnostic requires macOS with Xcode")
        prepared = p0.prepare(output, source, rendering.command)
        manifest["sourceSHA256"] = prepared["sourceSHA256"]
        info = plistlib.loads((output / "p0-signin/project/Info.plist").read_bytes())
        if info.get("LCBuilderCommit") != manifest["builderCommit"]:
            raise ValueError("Diagnostic fixture commit differs from checkout")
        if prepared["sourceSHA256"].get("generated-shell") != manifest["sourceGeneration"]["generatedSourceSHA256"]:
            raise ValueError("Diagnostic build source differs from production generation")
        phones = [row for row in rendering.available_devices() if row[0] == "phone"]
        if len(phones) != 1:
            raise ValueError("Diagnostic requires exactly one selected phone")
        _, device, runtime = phones[0]
        manifest["device"] = {"udid": device, "runtime": runtime}
        states = json.loads(rendering.command("xcrun", "simctl", "list", "devices", "--json"))
        matches = [item for group in states["devices"].values() for item in group if item["udid"] == device]
        if len(matches) != 1 or matches[0]["state"] != "Shutdown":
            raise ValueError("Cold-launch diagnostic requires a shutdown simulator; no existing device is reset")
        owned = True
        rendering.command("xcrun", "simctl", "boot", device)
        rendering.wait_for_simulator_boot(device)
        for observation in manifest["observations"]:
            # Always execute both fixed observations, even if the first fails.
            # Request one method in each invocation. XCTest may restart after
            # a crash; retain its complete summary/log rather than hide that.
            destination = output / observation["name"]
            destination.mkdir()
            observation["status"] = "running"
            write_json(path, manifest)
            try:
                report = p0.execute(prepared, "phone", device, destination, rendering.command,
                                    diagnostic_case="credentials-default")
                observation["report"] = report
                observation["executionSucceeded"] = report.get("diagnosticExecutionSucceeded") is True
                observation["status"] = "completed"
            except Exception as error:
                observation["status"] = "failed"
                observation["executionSucceeded"] = False
                observation["error"] = str(error)
            write_json(path, manifest)
        if rendering.command("git", "-C", str(ROOT), "rev-parse", "HEAD") != manifest["builderCommit"]:
            raise ValueError("Builder commit changed during diagnostic")
        if input_hashes() != manifest["inputSHA256"] or p0.digest(source) != manifest["sourceGeneration"]["generatedSourceSHA256"]:
            raise ValueError("Diagnostic source inputs changed during execution")
        manifest["diagnosticCompleted"] = all(row["status"] == "completed" for row in manifest["observations"])
    except Exception as error:
        manifest["failures"].append(str(error))
    except BaseException as error:
        manifest["failures"].append("Interrupted: " + type(error).__name__)
        raise
    finally:
        if owned:
            if all(row["status"] == "not-started" for row in manifest["observations"]):
                try:
                    p0.capture_diagnostics(output / "p0-signin", "phone", device, None, rendering.command)
                except Exception as error:
                    manifest["failures"].append("Boot diagnostics: " + str(error))
            try:
                rendering.command("xcrun", "simctl", "shutdown", device)
                manifest["ownedShutdownSucceeded"] = True
            except Exception as error:
                manifest["ownedShutdownSucceeded"] = False
                manifest["failures"].append("Owned simulator shutdown: " + str(error))
        manifest["allObservationsSucceeded"] = manifest["diagnosticCompleted"] and not manifest["failures"] and all(
            row.get("executionSucceeded") is True for row in manifest["observations"])
        try:
            write_json(path, manifest)
        finally:
            rendering.COMMAND_LOG = previous_log
    return manifest


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True, help="Fresh, dedicated preflight evidence directory")
    parser.add_argument("--v3-source", type=Path,
                        help="Optional prepared production shell; require exact P0 extraction equivalence")
    parser.add_argument("--input-diagnostic", action="store_true",
                        help="Only two one-shot phone credentials-default observations; never acceptance")
    args = parser.parse_args(argv)
    try:
        if args.input_diagnostic:
            if args.v3_source:
                raise ValueError("Diagnostic mode does not accept a prepared-host override")
            manifest = run_input_diagnostic(args.output)
            print(json.dumps({key: manifest[key] for key in (
                "mode", "passed", "releaseEligible", "diagnosticCompleted", "allObservationsSucceeded", "failures")}), flush=True)
            return 0 if manifest["allObservationsSucceeded"] else 1
        manifest = run(args.output, args.v3_source)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(json.dumps({key: manifest[key] for key in (
        "mode", "passed", "releaseEligible", "caseCount", "screenshotCount", "failures")}), flush=True)
    return 0 if manifest["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
